kino/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('serial.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

serial/urls.py
from django.urls import path
from .views import get_info, get_products, detail, add_products, update_products,delete_product


app_name = 'products'
urlpatterns = [
    path('', get_info, name='get_info'),
    path('products/<int:pk>', get_products, name='get_products'),
    path('products/detail/<int:pk>', detail, name='detail'),
    path('add_products', add_products, name='add_products'),
    path('update/<int:pk>', update_products, name='update'),
      path('delete/<int:pk>', delete_product, name='delete_product'),
]

serial/models.py
from django.db import models

# Create your models here.


class Serial_Name(models.Model):
    name=models.CharField(max_length=20)


    class Meta:
        db_table='serial'

    def __str__(self) -> str:
        return self.name





class Get_Actior(models.Model):
    serial=models.ForeignKey(to='Serial_Name',on_delete=models.CASCADE)
    actior_name=models.CharField(max_length=20)
    yera=models.IntegerField()
    gender=models.CharField(10)
    image=models.ImageField(upload_to='rasm/',blank=True,null=True)


    class Meta:
        db_table='aktior'

    def __str__(self) -> str:
        return f"{self.serial.name}  {self.actior_name}"
    
        

serial/forms.py
from django.forms import ModelForm
from .models import Get_Actior


class ProductForm(ModelForm):
    class Meta:
        model = Get_Actior
        fields = '__all__'

serial/views.py
from django.shortcuts import render, redirect
from .forms import ProductForm
from .models import Serial_Name, Get_Actior
# Create your views here.


def get_info(request):
    categories = Serial_Name.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'index.html', context=context)

def get_products(request, pk):
    products = Get_Actior.objects.filter(serial=pk)
    context = {
        'products': products
    }
    return render(request, 'products.html', context=context)

def detail(request, pk):
    product = Get_Actior.objects.get(pk=pk)
    context = {
        'product': product
    }
    return render(request, 'detail.html', context=context)

def add_products(request):
    form = ProductForm(request.POST, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('products:get_info')
    context = {
        'form': form
        }
    return render(request, 'create.html', context=context)


def update_products(request, pk):
    data = Get_Actior.objects.get(pk=pk)
    form = ProductForm(request.POST, request.FILES, instance=data)
    if form.is_valid():
        print(1)
        form.save()
        return redirect('products:get_info')
    context = {
        'form': form
        }
    return render(request, 'update.html', context=context)




from django.shortcuts import get_object_or_404

def delete_product(request, pk):
    product = get_object_or_404(Get_Actior, pk=pk)
    
    if request.method == 'POST':
        product.delete()
        return redirect('products:get_info')
    
    return render(request, 'delete.html', {'product': product})

templates/create.html
<form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Save</button>
</form>

templates/delete.html
<form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Delete</button>
</form>

templates/detail.html
<title>Detail</title>



<body>
<img src="{{ product.image.url }}"/><br>
Actior_name:{{ product.actior_name }}<br>
year:{{ product.yera }}<br>
Gender:{{ product.gender }}
       <hr/>

<a href="{% url 'products:get_info'%}" >home</a><br>
<a href="{% url 'products:update' product.pk %}" >Update</a><br>
<a href="{% url 'products:delete_product' product.pk %}" >Delete</a><br>


</body>

templates/index.html
<title>Home Page</title>

<h1>Home Page</h1><br>

<h3>Categories</h3><br>

<body>
{% for category in categories %}
<a href="{% url 'products:get_products' category.pk %}" >{{ category.name }}</a><br>
{% endfor %}
<a href="{% url 'products:add_products' %}" ><b>Add Products</b></a><br>


</body>

templates/products.html
<title>Products</title>

<h1>Serial Actiorlari</h1><br>


<body>
{% for product in products %}
    <a href="{% url 'products:detail' product.pk %}" >{{ product.actior_name }}</a><hr>
{% endfor %}

</body>

templates/update.html
<form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Save</button>
</form>